name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Important for JamesIves/github-pages-deploy-action

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install npm dependencies
        run: npm ci
      
      - name: Build with webpack
        run: |
          NODE_ENV=production npm run build:webpack
          # Make sure the bundle.js files are in the repository
          git checkout -- js/ || true
          ls -la js/
        
      - name: Debug directory structure
        run: |
          echo "Checking for js directory and bundle.js"
          ls -la js/ || echo "No js directory found!"
          echo "Current directory structure"
          find . -type f -name "bundle.js" -o -name "*.js.map" | sort
      
      - name: Ensure js directory is included for Jekyll
        run: |
          # Make sure the js directory exists
          mkdir -p js
          # Create a backup of the bundle.js files if they don't exist
          [ -f js/bundle.js ] || echo "Creating empty bundle.js files for safety"
          [ -f js/bundle.js ] || touch js/bundle.js
          [ -f js/bundle.js.map ] || touch js/bundle.js.map
          chmod 644 js/bundle.js js/bundle.js.map
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Install Jekyll dependencies
        run: bundle install
      
      - name: Build Jekyll site
        run: |
          # Ensure the js directory is included in Jekyll build
          bundle exec jekyll build
          # Debug _site contents to verify js files were included
          echo "Contents of _site/js directory:"
          ls -la _site/js/ || echo "No js directory found in _site!"
          # Copy js files directly to _site if not there
          if [ ! -f _site/js/bundle.js ]; then
            echo "Manually copying js files to _site/js/"
            mkdir -p _site/js/
            cp js/bundle.js _site/js/
            cp js/bundle.js.map _site/js/
          fi
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _site
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true  # Only remove files that are in the target branch but not in the source folder
          clean-exclude: |
            .git
            .github 